### ISSUE TITLE
qalc doesn't work as expected on all platforms

### ISSUE THREAD

**Issue by ballerburg9005** [644/iqcaptcha-buster#2]
From Docker image with debian/latest:

```
# qalc -t "32x + 9 + x where x=1"
0
# qalc --version
2.8.2

aarch64 Debian 10.9
```

My home PC:
```
% qalc -t "32x + 9 + x where x=1"
42
% qalc --version
3.17.0

x86_64 Archlinux
```

**Comment by 644** [comment]
Compile latest qalc or use an OS that supports latest versions. I plan on making a public API and writing everything in PHP/JS at some point anyway, given that captchas are still possible to solve automatically.
