### ISSUE TITLE
never gets the Raven's matrix right

### ISSUE THREAD

**Issue by ballerburg9005** [644/iqcaptcha-buster#3]
![tmp](https://user-images.githubusercontent.com/50874674/114891396-21468d00-9e0c-11eb-908d-60e5d15a85cf.jpg)

This is raven1 (x=5)

```
# ./get-solution 1
20859.2 : tmp.png
50.4:raven23.gif
1579.5:raven6.gif
2751.4:raven16.gif
4097.6:raven1.jpg
5987:raven7.gif
6893.4:raven8.gif
7168.7:raven0.jpg
8045.8:raven3.jpg
8395.9:raven20.gif
8619.6:raven3.gif
8678.1:raven13.gif
8983:raven24.gif
9521.5:raven2.jpg
10798.5:raven5.gif
10855.7:raven18.gif
11151.2:raven17.gif
11665.2:raven10.gif
11843.7:raven21.gif
11994.6:raven11.gif
12406.4:raven22.gif
12673.9:raven12.gif
12692.9:raven9.gif
13573.8:raven14.gif
14152.6:raven4.jpg
14207:raven15.gif
14322.2:raven4.gif
14845.9:raven19.gif

x=1
```

![tmp](https://user-images.githubusercontent.com/50874674/114892856-6dde9800-9e0d-11eb-9c2b-4ce95a20db14.jpg)

This is raven2 (x=4)

```
./get-solution 1
25040.1 : tmp.png
4231.3:raven23.gif
5340.6:raven2.jpg
5760.4:raven6.gif
6932.3:raven16.gif
8278.5:raven1.jpg
10167.9:raven7.gif
11074.3:raven8.gif
11349.6:raven0.jpg
12226.7:raven3.jpg
12576.8:raven20.gif
12800.5:raven3.gif
12859:raven13.gif
13163.9:raven24.gif
14979.4:raven5.gif
15036.6:raven18.gif
15332:raven17.gif
15846.1:raven10.gif
16024.6:raven21.gif
16175.5:raven11.gif
16587.3:raven22.gif
16854.8:raven12.gif
16873.8:raven9.gif
17754.7:raven14.gif
18333.5:raven4.jpg
18387.9:raven15.gif
18503.1:raven4.gif
19026.8:raven19.gif

x=1
```

![tmp](https://user-images.githubusercontent.com/50874674/114893332-e04f7800-9e0d-11eb-92e5-f690dbe71c1f.jpg)

This is raven23 (x=1)

```
./get-solution 1
18710.4 : tmp.png
569.3:raven6.gif
602.6:raven16.gif
1948.8:raven1.jpg
2098.4:raven23.gif
3838.2:raven7.gif
4744.6:raven8.gif
5019.9:raven0.jpg
5897:raven3.jpg
6247.1:raven20.gif
6470.8:raven3.gif
6529.3:raven13.gif
6834.2:raven24.gif
8649.7:raven5.gif
8706.9:raven18.gif
9002.35:raven17.gif
9516.36:raven10.gif
9694.91:raven21.gif
9845.78:raven11.gif
10257.6:raven22.gif
10525.1:raven12.gif
10544.1:raven9.gif
11425:raven14.gif
11670.3:raven2.jpg
12003.8:raven4.jpg
12058.2:raven15.gif
12173.4:raven4.gif
12697.1:raven19.gif

x=5
```

![tmp](https://user-images.githubusercontent.com/50874674/114893570-1ee53280-9e0e-11eb-8c8a-db2617890b19.jpg)

This is raven17 (x=4)

```
./get-solution 1
8440.9 : tmp.png
11.86:raven22.gif
255.55:raven12.gif
274.62:raven9.gif
423.72:raven11.gif
574.59:raven21.gif
753.14:raven10.gif
1155.48:raven14.gif
1267.15:raven17.gif
1562.6:raven18.gif
1619.8:raven5.gif
1734.34:raven4.jpg
1788.74:raven15.gif
1903.93:raven4.gif
2427.63:raven19.gif
3435.3:raven24.gif
3740.2:raven13.gif
3798.7:raven3.gif
4022.4:raven20.gif
4372.5:raven3.jpg
5249.6:raven0.jpg
5524.9:raven8.gif
6431.3:raven7.gif
8320.7:raven1.jpg
9666.9:raven16.gif
10838.8:raven6.gif
12367.9:raven23.gif
21939.8:raven2.jpg

x=5
```

**Comment by 644** [comment]
Have imagemagick >7.0+ installed, and it will occasionally fail, but that's the purpose of the retry feature. I've rarely had to retry more than once or twice.

**Comment by ballerburg9005** [comment]
The results between Imagemagick versions are identical. 

I tried 10 times and it didn't even work once, not even by chance. I think with the distortion, it gets hung up on certain answers. So it will predominantly indentify the challenge as raven22 or raven6, but rarely other solutions.

By default you only have 3 tries per session, and the IP limit currently defaults to 50 tries.

**Comment by 644** [comment]
Like I said, there's a retry feature, which will iterate through the list. Try ./get-solution 2 for raven2. It returns x=4 correctly, and in most cases it's within the first 4. Once tesseract is added, there's nothing stopping mass, automated requests from a string of proxies. Nothing at all.

**Comment by ballerburg9005** [comment]
Like I said, the limit per IP is 50 tries per hour or so. This does stop mass automated requests entirely. But it is unfair to people who can't affort a real IP address and are behind carrier NAT. Hence the generous 50. 

Good luck getting an array of public free proxies to work in any usable manner. After 3 month from your list of 100 curated proxies, only 15 are still working. After 6 month maybe 10. Timeouts alone will kill you. I mean you could potentially pull it off, if you are babysitting it as your personal pet project public webservice, with private botnets or something. But come on. This is unrealistic.

Also I could seed x from 1-8 to 1-100 and fix the minor hole where f'''(x) is zero. It would somewhat suck though. So far 90% of the time you could do the math in your head easily. When seeded you always need to use a calculator.

**Comment by 644** [comment]
Proxies are extremely cheap. I know one site that offers 1000 fresh proxies per week for $40 a month. And adding 100 options would actually make my script more accurate. Or if you just mean selecting 8 random values between 1-100 it wouldn't affect my script.

As for free curated proxies, I've written scripts in the past that search websites and github for dumps, then tests them in bulk with gnu parallel. No need to babysit when I can use cronjobs.

**Comment by ballerburg9005** [comment]
Let me quickly code what I mean...

**Comment by ballerburg9005** [comment]
![captcha](https://user-images.githubusercontent.com/50874674/114915701-30393980-9e24-11eb-8e58-63a02ec37cb7.jpg)

If we also do math-eval the answer, it isn't that big of a nuisance.

Anyway, I won't waste further time on this since I will replace the big picture with totally random Raven's matrices from [the other iqcatcha](https://github.com/kxgh/kx-iqcaptcha) in the future.


> Proxies are extremely cheap. I know one site that offers 1000 fresh proxies per week for $40 a month.

Hahahaha.

Thanks for trying!

**Comment by 644** [comment]
Tesseract is amazingly good at finding text in captchas, it only really struggled with the superscripts in the equation from my testing.

Also, those captchas on the other iq captcha look quite easy to solve by using histogram and shape comparisons after doing some imagemagick cleaning. They only really want to filter out lazy users though so there's a big difference.

Failing that there's AI. It's great with these types of captchas.

Failing that, well, there's 2captcha..

There's really nothing you can do. Someone will always find ways around. If you ever do manage to invent something that can't be automated or bypassed in some way you'll make millions. But since you're releasing under GPL3, I really don't think you'll actually make money even if you did. It would just get stolen. And besides, your IQ clearly isn't high enough to invent something like that anyway.

But you did a good good job making it even more hideous. A truly smart person would take one look at that and go "ugh, not worth my time", and move on. You may filter out some extremely stupid people, but you'll also drive away a lot of smart ones. What you'll end up with is a community filled with people of average intelligence, claiming to be high-IQ and extremely intelligent because they're allowed to post there. Basically r/iamverysmart.

**Comment by 644** [comment]
But never fear, I is here! I'll save you from yourself and keep breaking your captcha. It will be fun.
